[package]
name = "pgrust01"
version = "0.1.0"
edition = "2021"


[dependencies]
chrono = "0.4.38"
sqlx = { version = "0.8.2", features = ["postgres", "runtime-tokio-native-tls", "chrono"] }
tokio = { version = "1", features = ["full"] }
